package net.runelite.client.plugins.microbot.magic.aiomagic.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.ItemID;

@Getter
@RequiredArgsConstructor
public enum Jewellery {
    SAPPHIRE_RING(ItemID.SAPPHIRE_RING, ItemID.RING_OF_RECOIL),
    SAPPHIRE_NECKLACE(ItemID.SAPPHIRE_NECKLACE, ItemID.GAMES_NECKLACE8),
    SAPPHIRE_BRACELET(ItemID.SAPPHIRE_BRACELET, ItemID.BRACELET_OF_CLAY),
    SAPPHIRE_AMULET(ItemID.SAPPHIRE_AMULET, ItemID.AMULET_OF_MAGIC),

    OPAL_RING(ItemID.OPAL_RING, ItemID.RING_OF_PURSUIT),
    OPAL_NECKLACE(ItemID.OPAL_NECKLACE, ItemID.DODGY_NECKLACE),
    OPAL_BRACELET(ItemID.OPAL_BRACELET, ItemID.EXPEDITIOUS_BRACELET),
    OPAL_AMULET(ItemID.OPAL_AMULET, ItemID.AMULET_OF_BOUNTY),

    EMERALD_RING(ItemID.EMERALD_RING, ItemID.RING_OF_DUELING8),
    EMERALD_NECKLACE(ItemID.EMERALD_NECKLACE, ItemID.BINDING_NECKLACE),
    EMERALD_BRACELET(ItemID.EMERALD_BRACELET, ItemID.CASTLE_WARS_BRACELET3),
    EMERALD_AMULET(ItemID.EMERALD_AMULET, ItemID.AMULET_OF_DEFENCE),

    JADE_RING(ItemID.JADE_RING, ItemID.RING_OF_RETURNING5),
    JADE_NECKLACE(ItemID.JADE_NECKLACE, ItemID.NECKLACE_OF_PASSAGE5),
    JADE_BRACELET(ItemID.JADE_BRACELET, ItemID.FLAMTAER_BRACELET),
    JADE_AMULET(ItemID.JADE_AMULET, ItemID.AMULET_OF_CHEMISTRY),

    RUBY_RING(ItemID.RUBY_RING, ItemID.RING_OF_FORGING),
    RUBY_NECKLACE(ItemID.RUBY_NECKLACE, ItemID.DIGSITE_PENDANT_5),
    RUBY_BRACELET(ItemID.RUBY_BRACELET, ItemID.INOCULATION_BRACELET),
    RUBY_AMULET(ItemID.RUBY_AMULET, ItemID.AMULET_OF_STRENGTH),

    TOPAZ_RING(ItemID.TOPAZ_RING, ItemID.EFARITAYS_AID),
    TOPAZ_NECKLACE(ItemID.TOPAZ_NECKLACE, ItemID.NECKLACE_OF_FAITH),
    TOPAZ_BRACELET(ItemID.TOPAZ_BRACELET, ItemID.BRACELET_OF_SLAUGHTER),
    TOPAZ_AMULET(ItemID.TOPAZ_AMULET, ItemID.BURNING_AMULET5),

    DIAMOND_RING(ItemID.DIAMOND_RING, ItemID.RING_OF_LIFE),
    DIAMOND_NECKLACE(ItemID.DIAMOND_NECKLACE, ItemID.PHOENIX_NECKLACE),
    DIAMOND_BRACELET(ItemID.DIAMOND_BRACELET, ItemID.ABYSSAL_BRACELET5),
    DIAMOND_AMULET(ItemID.DIAMOND_AMULET, ItemID.AMULET_OF_POWER),

    DRAGONSTONE_RING(ItemID.DRAGONSTONE_RING, ItemID.RING_OF_WEALTH),
    DRAGONSTONE_NECKLACE(ItemID.DRAGON_NECKLACE, ItemID.SKILLS_NECKLACE),
    DRAGONSTONE_BRACELET(ItemID.DRAGONSTONE_BRACELET, ItemID.COMBAT_BRACELET),
    DRAGONSTONE_AMULET(ItemID.DRAGONSTONE_AMULET, ItemID.AMULET_OF_GLORY),

    ONYX_RING(ItemID.ONYX_RING, ItemID.RING_OF_STONE),
    ONYX_NECKLACE(ItemID.ONYX_NECKLACE, ItemID.BERSERKER_NECKLACE),
    ONYX_BRACELET(ItemID.ONYX_BRACELET, ItemID.REGEN_BRACELET),
    ONYX_AMULET(ItemID.ONYX_AMULET, ItemID.AMULET_OF_FURY),

    ZENYTE_RING(ItemID.ZENYTE_RING, ItemID.RING_OF_SUFFERING),
    ZENYTE_NECKLACE(ItemID.ZENYTE_NECKLACE, ItemID.NECKLACE_OF_ANGUISH),
    ZENYTE_BRACELET(ItemID.ZENYTE_BRACELET, ItemID.TORMENTED_BRACELET),
    ZENYTE_AMULET(ItemID.ZENYTE_AMULET, ItemID.AMULET_OF_TORTURE);

    private final int normalId;
    private final int enchantedId;
}
